import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { GoogleTagManager } from "@/components/tracking/GoogleTagManager";
import { IS_GTM_ENABLED } from "@/libs/tracking/config.tracking";
import { RootInnerLayout } from "@/components/layouts/RootInnerLayout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {IS_GTM_ENABLED && <GoogleTagManager />}
        <RootInnerLayout>{children}</RootInnerLayout>
      </body>
    </html>
  );
}
